import manifest from "../../assets/sfx/manifest.json";

export const SFX_IDS = ["whoosh", "swoosh", "pop", "click", "ding", "beep", "riser", "drop", "tick", "chime"] as const;
export type SfxId = (typeof SFX_IDS)[number];

export interface SfxEntry { label: string; durationSec: number; file: number }

const entries = (manifest as { sounds: { id: string; label: string; durationSec: number }[] }).sounds;
const info = (id: SfxId) => {
  const e = entries.find((s) => s.id === id);
  if (!e) throw new Error(`sfx manifest is missing ${id}`);
  return { label: e.label, durationSec: e.durationSec };
};

// Metro needs static require() calls, one per file. Generated by scripts/generate-sfx.mjs
// (see assets/sfx/README.md).
export const SFX: Record<SfxId, SfxEntry> = {
  whoosh: { ...info("whoosh"), file: require("../../assets/sfx/whoosh.wav") },
  swoosh: { ...info("swoosh"), file: require("../../assets/sfx/swoosh.wav") },
  pop: { ...info("pop"), file: require("../../assets/sfx/pop.wav") },
  click: { ...info("click"), file: require("../../assets/sfx/click.wav") },
  ding: { ...info("ding"), file: require("../../assets/sfx/ding.wav") },
  beep: { ...info("beep"), file: require("../../assets/sfx/beep.wav") },
  riser: { ...info("riser"), file: require("../../assets/sfx/riser.wav") },
  drop: { ...info("drop"), file: require("../../assets/sfx/drop.wav") },
  tick: { ...info("tick"), file: require("../../assets/sfx/tick.wav") },
  chime: { ...info("chime"), file: require("../../assets/sfx/chime.wav") },
};
